### ISSUE TITLE
autocomplete fails

### ISSUE THREAD

**Issue by plambert** [davidchalifoux/kaput-cli#2]
I am unable to get any autocomplete commands to work, with or without a shell argument.

Any idea what I should try, what might be wrong?

Paul

```
$ kaput autocomplete
Building the autocomplete cache... !
TypeError: Cannot read property 'replace' of null
    at sanitizeDescription (/usr/local/lib/node_modules/kaput-cli/node_modules/@oclif/plugin-autocomplete/lib/commands/autocomplete/create.js:12:10)
    at /usr/local/lib/node_modules/kaput-cli/node_modules/@oclif/plugin-autocomplete/lib/commands/autocomplete/create.js:113:45
    at Array.map (<anonymous>)
    at Create.genZshFlagSpecs (/usr/local/lib/node_modules/kaput-cli/node_modules/@oclif/plugin-autocomplete/lib/commands/autocomplete/create.js:108:14)
    at /usr/local/lib/node_modules/kaput-cli/node_modules/@oclif/plugin-autocomplete/lib/commands/autocomplete/create.js:135:12
    at Array.map (<anonymous>)
    at Create.get genCaseStatementForFlagsMetaString [as genCaseStatementForFlagsMetaString] (/usr/local/lib/node_modules/kaput-cli/node_modules/@oclif/plugin-autocomplete/lib/commands/autocomplete/create.js:132:30)
    at Create.get zshCompletionFunction [as zshCompletionFunction] (/usr/local/lib/node_modules/kaput-cli/node_modules/@oclif/plugin-autocomplete/lib/commands/autocomplete/create.js:209:48)
    at Create.createFiles (/usr/local/lib/node_modules/kaput-cli/node_modules/@oclif/plugin-autocomplete/lib/commands/autocomplete/create.js:37:65)
    at async Create.run (/usr/local/lib/node_modules/kaput-cli/node_modules/@oclif/plugin-autocomplete/lib/commands/autocomplete/create.js:23:9)
```

**Comment by davidchalifoux** [comment]
Yeah I’m aware of this. Just kinda threw it in right before releasing without testing it thoroughly. 

I’ll look into resolving it.

**Comment by davidchalifoux** [comment]
In https://github.com/davidchalifoux/kaput-cli/commit/76ce9a22cfc6b410d1e4c1da1466f52ec82c4719 I just decided to remove the plugin as I feel like the support isn't good enough to leave in.

I might revisit adding autocomplete in at a later date.
